version: '3'
services:
  dgraph:
    image: dgraph/standalone:v21.03.0
    ports:
      - "8060:8080"
      - "9060:9080"
  grbac:
    build: ../../
    entrypoint: /usr/local/grbac/docker-compose.sh
    ports:
      - "9070:9080"
