name: Animeshon gRBAC

on:
  push:
    branches: [master]
  release:
    types: [published]

jobs:
  docker:
    environment: release
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repository code
        uses: actions/checkout@v2

      - name: Set up Docker versioning labels and tags
        id: docker-metadata
        uses: docker/metadata-action@v3
        with:
          images: grbac/grbac
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.docker-metadata.outputs.tags }}
          labels: ${{ steps.docker-metadata.outputs.labels }}
